version: "3"
services:
  spark-master:
    image: "xiongjun19/spark_master:0.0.2"
    ports:
      - "8080:8080"
    volumes:
      - "/data/tmp_data:/data/tmp_data"
    networks:
      - spark-net
    deploy:
      resources:
        limits:
          cpus: "1"
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints:
          - node.labels.role==master
  spark-worker:
    image: "xiongjun19/spark_worker:0.0.2"
    ports:
      - "8081:8081"
    volumes:
      - "/data/tmp_data:/data/tmp_data"
    environment:
      - CORES=2
      - MEMORY=15G
    deploy:
      resources:
        limits:
          cpus: "1"
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints:
          - node.labels.role==worker
      replicas: 2 
    networks:
      - spark-net
networks:
  spark-net:
    driver: overlay
    external: true
